import type { VarCardManifest } from "./types"
import { toVarCardRecordType } from "./types"

const builtinCards: VarCardManifest[] = [
  {
    id: "current-time",
    namespace: "builtin",
    version: "1.0.0",
    title: "Current Time",
    description: "Displays the current timestamp for record entries.",
    icon: "time-outline",
    tags: ["time", "timestamp", "live"],
    readonly: true,
    baseCardId: null,
    recordType: toVarCardRecordType("builtin", "current-time"),
    demoValue: "2026-03-20T12:00:00.000Z",
    schema: {
      kind: "datetime",
      label: "Recorded At",
      placeholder: null,
      defaultValue: null,
      helperText: "Populated from the current clock when used in live mode.",
      unit: null,
      format: "iso",
      rows: null,
      min: null,
      max: null,
      step: null,
      language: null,
      options: [],
    },
    layout: { variant: "inline", density: "compact", align: "start" },
    appearance: { accentColor: "#2563eb", icon: "time-outline", badge: "Built-in" },
    behavior: { allowManualInput: false, allowCopy: true, liveValue: true },
  },
  {
    id: "user-name",
    namespace: "builtin",
    version: "1.0.0",
    title: "User Name",
    description: "Captures the operator name as a short text field.",
    icon: "person-outline",
    tags: ["identity", "operator", "text"],
    readonly: true,
    baseCardId: null,
    recordType: toVarCardRecordType("builtin", "user-name"),
    demoValue: "Ava Chen",
    schema: {
      kind: "text",
      label: "Operator",
      placeholder: "Enter name",
      defaultValue: "",
      helperText: "Use for manual operator attribution.",
      unit: null,
      format: null,
      rows: null,
      min: null,
      max: null,
      step: null,
      language: null,
      options: [],
    },
    layout: { variant: "inline", density: "comfortable", align: "stretch" },
    appearance: { accentColor: "#0f766e", icon: "person-outline", badge: "Built-in" },
    behavior: { allowManualInput: true, allowCopy: true, liveValue: false },
  },
  {
    id: "markdown-note",
    namespace: "builtin",
    version: "1.0.0",
    title: "Markdown Note",
    description: "Supports richer formatted notes in markdown syntax.",
    icon: "document-text-outline",
    tags: ["markdown", "notes", "rich-text"],
    readonly: true,
    baseCardId: null,
    recordType: toVarCardRecordType("builtin", "markdown-note"),
    demoValue: "## Observation\n\nCells reached 80% confluence.",
    schema: {
      kind: "markdown",
      label: "Observation",
      placeholder: "Write notes in markdown",
      defaultValue: "",
      helperText: "Use markdown formatting for headings, lists, and emphasis.",
      unit: null,
      format: null,
      rows: 6,
      min: null,
      max: null,
      step: null,
      language: null,
      options: [],
    },
    layout: { variant: "panel", density: "comfortable", align: "stretch" },
    appearance: { accentColor: "#7c3aed", icon: "document-text-outline", badge: "Built-in" },
    behavior: { allowManualInput: true, allowCopy: true, liveValue: false },
  },
  {
    id: "dna-sequence",
    namespace: "builtin",
    version: "1.0.0",
    title: "DNA Sequence",
    description: "Stores nucleotide sequences with sequence-specific semantics.",
    icon: "flask-outline",
    tags: ["sequence", "dna", "bio"],
    readonly: true,
    baseCardId: null,
    recordType: toVarCardRecordType("builtin", "dna-sequence"),
    demoValue: "ATGCGTACCGTTAA",
    schema: {
      kind: "dna",
      label: "Sequence",
      placeholder: "ATGC...",
      defaultValue: "",
      helperText: "Accepts nucleotide characters for sequence capture.",
      unit: "bp",
      format: null,
      rows: 4,
      min: null,
      max: null,
      step: null,
      language: null,
      options: [],
    },
    layout: { variant: "panel", density: "comfortable", align: "stretch" },
    appearance: { accentColor: "#dc2626", icon: "flask-outline", badge: "Built-in" },
    behavior: { allowManualInput: true, allowCopy: true, liveValue: false },
  },
  {
    id: "code-snippet",
    namespace: "builtin",
    version: "1.0.0",
    title: "Code Snippet",
    description: "Captures code-like content with language metadata.",
    icon: "code-slash-outline",
    tags: ["code", "script", "developer"],
    readonly: true,
    baseCardId: null,
    recordType: toVarCardRecordType("builtin", "code-snippet"),
    demoValue: "print('hello world')",
    schema: {
      kind: "code",
      label: "Script",
      placeholder: "Write code",
      defaultValue: "",
      helperText: "Use for small scripts or expression snippets.",
      unit: null,
      format: null,
      rows: 8,
      min: null,
      max: null,
      step: null,
      language: "python",
      options: [],
    },
    layout: { variant: "panel", density: "comfortable", align: "stretch" },
    appearance: { accentColor: "#ea580c", icon: "code-slash-outline", badge: "Built-in" },
    behavior: { allowManualInput: true, allowCopy: true, liveValue: false },
  },
]

export function getBuiltinVarCardManifests(): VarCardManifest[] {
  return builtinCards.map((card) => ({
    ...card,
    tags: [...card.tags],
    schema: {
      ...card.schema,
      options: card.schema.options.map((option) => ({ ...option })),
    },
    layout: { ...card.layout },
    appearance: { ...card.appearance },
    behavior: { ...card.behavior },
  }))
}
